FROM ubuntu:16.04

MAINTAINER Ganesh Raskar "https://geewhocodes.me"

RUN apt-get update -qq \
 && apt-get install --no-install-recommends -y \
    # essentials
    build-essential \
    g++ \
    git \
    openssh-client \
    # py 3
    python3 \
    python3-dev \
    python3-pip \
    python3-setuptools \
    python3-virtualenv \
    python3-wheel \
    pkg-config \
    libopenblas-base \
    # web
    libapache2-mod-wsgi \
    python-dev \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

RUN mkdir gwcml && cd gwcml



COPY ./webapp/requirements.txt /tmp/requirements.txt

RUN pip install -r /tmp/requirements.txt

COPY ./webapp /var/www/webapp

WORKDIR /var/www/webapp

EXPOSE 80

CMD python main.py